### PR TITLE
fix format name

### PR DESCRIPTION
**Pull request by gioman**

### CODE REVIEW

**Comment by alexbruy** [comment]
Are you sure this is correct fix? With GDAL 2.1.0 I got "CartoDB" as format name

**Comment by gioman** [comment]
> Are you sure this is correct fix? With GDAL 2.1.0 I got "CartoDB" as format name

in GDAL 2.1.2 is "Carto"

Carto -vector- (rw+): Carto

**Comment by alexbruy** [comment]
Ah, ok. If we have GDAL 2.1.2 in out installer then it is safe fix. Otherwise we will need to add condition and check GDAL version

**Comment by gioman** [comment]
> Ah, ok. If we have GDAL 2.1.2 in out installer then it is safe fix. Otherwise we will need to add condition and check GDAL version

yes, new builds have gdal 2.1.2

**Pull request merged**
